### ISSUE TITLE
Remove AMP feature not working anymore

### ISSUE THREAD

**Issue by jmevel** [kiwibrowser/src#88] opened 2020-05-12 07:08 UTC
I love the *Remove AMP* feature in Kiwi Browser, it's actually what made me switch from Chrome on my Android. 
However it seems now this feature isn't working anymore.

## Steps to reproduce
- Go to `Settings -> Privacy` and check `Remove AMP`
- Go to Google news and click on some articles (for example The New York Times)

## Actual Behavior
The article's URL is like `https://news.google.com/articles/[...]`

## Expected Behavior
The article is the website's URL like `https://www.nytimes.com/[...]`

I hope a Kiwi's developer could find a way to fix this.
By the way great browser, having extensions and a native Ad Blocker is awesome!

**Comment by hjyoung1** [comment] 2020-05-12 07:23
Duplicate of https://github.com/kiwibrowser/src/issues/54

**Closed** 2020-05-20 21:49 UTC
Labels: Duplicate
