### ISSUE TITLE
Add option to enable Extensions in Incognito mode

### ISSUE THREAD

**Issue by tolotrasamuel** [kiwibrowser/src#70] opened 2020-04-25 17:16 UTC
In Chrome browser, there is an option to enable extensions in Incognito mode.
It would be useful if this feature is also available on Kiwi. It should be disabled by default and enabled manually. 
Also, if privacy is an issue, we can add an optional UI indicating how many extensions are running that could monitor your data when browsing in Incognito mode. ( Something like a sticky header, icon, or even just the window color)

**Comment by hjyoung1** [comment] 2020-04-25 17:25
Option is already there (in extension - details) but it doesn't work properly.

**Comment by rururux** [comment] 2020-04-25 17:58
![Screenshot_20200426-024541~01](https://user-images.githubusercontent.com/5568054/80286798-76efd880-8768-11ea-9790-441d332d5629.png)

here.

**Comment by tolotrasamuel** [comment] 2020-04-25 18:46
Yes it is not working properly. I tried "Block Site - Website Blocker for Chrome". Not working in Incognito Mode. Also tried Tiny Web Filter. This one is working though.  
It is written "unselect this option" but I do not see a checkbox

**Comment by hjyoung1** [comment] 2020-04-25 19:12
Please close this. As it's duplicate of #36  
Use that issue to report.

**Comment by rururux** [comment] 2020-04-25 19:16
> It is written "unselect this option" but I do not see a checkbox

are you talking about this?
![1587841642663](https://user-images.githubusercontent.com/5568054/80288559-a6f0a900-8773-11ea-8058-a06c784feffa.jpg)

**Closed** 2020-04-25 21:18 UTC
Labels: Duplicate
