### ISSUE TITLE
Update to the latest Chromium version

### ISSUE THREAD

**Issue by v1nc** [kiwibrowser/src#109] opened 2020-06-03 07:19 UTC
Great Work!
Is there a specific reason why Kiwi is not based on the latest Chromium version 85?

**Comment by hjyoung1** [comment] 2020-06-03 07:30
Duplicate of https://github.com/kiwibrowser/src/issues/94

**Closed** 2020-06-03 07:51 UTC
Labels: feature_request

**Comment by kiwibrowser** [comment] 2020-06-06 14:08
@v1nc 

Planned, work will start on https://github.com/kiwibrowser/src.next
