### ISSUE TITLE
Suggest uploading to F-droid to let more people know and use

### ISSUE THREAD

**Issue by 1457384613gh** [kiwibrowser/src#363] opened 2021-05-25 05:23 UTC
Suggest uploading to F-droid to let more people know and use, and it is convenient for users to update.

**Comment by KaKi87** [comment] 2021-07-23 22:12
Duplicate of kiwibrowser/android#30.
Please post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).

**Closed by KaKi87** 2021-07-23 22:12 UTC
