### ISSUE TITLE
Copy / Paste problem

### ISSUE THREAD

**Issue by NekoGryphou** [kiwibrowser/src#121] opened 2020-06-23 08:16 UTC
When copying and pasting, if the browser is open, it does not take into account the last copy made from another application. 
Attached is an explanatory video
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40165444/85378478-e7ce2980-b53a-11ea-87cd-dcde58678914.gif)

**Comment by hjyoung1** [comment] 2020-06-23 08:28
Duplicate of #26

**Comment by borealis999** [comment] 2020-06-23 18:59
This is already a well-known issue in the Kiwi community. This additional issue is unnecessary.

**Closed** 2020-10-02 20:18 UTC
Labels: bug

**Comment by kiwibrowser** [comment] 2020-10-02 20:20
Testing a fix @ https://github.com/kiwibrowser/src/commit/8419f2f07faf34d416ca50d7f924413dd0eb2eac
