### ISSUE TITLE
F-Droid package

### ISSUE THREAD

**Issue by kayg04** [kiwibrowser/src#6] opened 2020-04-18 09:30 UTC
It's very refreshing to see a chromium browser going open source, one especially that has extensions support. Would it be possible to submit the package to the F-Droid repo? It would help people who are not so keen on downloading apps from google.

**Comment by kiwibrowser** [comment] 2020-04-18 10:09
In theory it's possible but before I think F-Droid should try to onboard Chromium (I think it's not the case) as Kiwi depends on Chromium

An alternative would be to create a F-Droid repo, if this is enough it's a possibility too

**Comment by PoorPocketsMcNewHold** [comment] 2020-04-18 10:52
An another alternative, would be to be inclued into an already managed F-Droid repo, like the @IzzySoft one : https://apt.izzysoft.de/fdroid/index/info
One downside would be that your F-Droid releases will depend on Izzy support obviously.

Outside of that, here´s how to create a F-Droid repo easily with the repomaker. https://www.f-droid.org/en/tutorials/create-repo

**Comment by IzzySoft** [comment] 2020-04-18 11:53
I'm afraid it won't fit into my repo because of the size limit. Reading "based upon Chromium", the APK will certainly be larger than 30M (the limit in mine).

But there's an F-Droid repo focused on web browsers [here](https://rfc2822.gitlab.io/fdroid-firefox/fdroid/repo/index.xml), maintained via [this GitLab repo](https://gitlab.com/rfc2822/fdroid-firefox). And it already mentions Kiwix, so it should fit: "Unofficial F-Droid repository for various apps, including Firefox, Kiwix and Signal"

**Comment by PoorPocketsMcNewHold** [comment] 2020-04-18 12:38
> I'm afraid it won't fit into my repo because of the size limit. Reading "based upon Chromium", the APK will certainly be larger than 30M (the limit in mine).
> 
> But there's an F-Droid repo focused on web browsers [here](https://rfc2822.gitlab.io/fdroid-firefox/fdroid/repo/index.xml), maintained via [this GitLab repo](https://gitlab.com/rfc2822/fdroid-firefox). And it already mentions Kiwix, so it should fit: "Unofficial F-Droid repository for various apps, including Firefox, Kiwix and Signal"

Thanks for the prompt reply, completely forgot that ¨unoficial mozilla repo¨ has changed. So yeah, in that case, maybe propose to serve built and officially signed applications to this repo.
I don’t think asking for this repo owner to make automated builds of the Kiwi Browser repo would work, as they are only redistributing official built APKs in an automated way.

**Comment by PoorPocketsMcNewHold** [comment] 2020-04-18 12:46
> And it already mentions Kiwix, so it should fit: "Unofficial F-Droid repository for various apps, including Firefox, Kiwix and Signal"

You’ve mistaken Kiwi Browser with [Kiwix](https://github.com/kiwix) which is a Wikipedia reader ! :laughing: 

Anyway, I´ve submitted an issue here on their repo : https://gitlab.com/rfc2822/fdroid-firefox/-/issues/8

**Comment by IzzySoft** [comment] 2020-04-18 12:53
> You’ve mistaken Kiwi Browser with Kiwix which is a Wikipedia reader !

No, I haven't (but I've waited for that comment :rofl:). If I had mistaken it, I had written "it's already there so what are you asking". I know what Kiwix is – and I've checked with your Readme in advance to see whether it relates. All I wanted to say is that repo is not restricted to Firefox and derivates (with which it originally started). And I wanted to have a laugh – so, mission accomplished :laughing:

All the best then! And thanks for considering my repo! :green_heart:

**Comment by kiwibrowser** [comment] 2020-04-18 13:12
I'll work on an automated build in the coming days (I need to read and understand how the GitHub CD pipeline works). Normally it shouldn't be difficult if you are interested into building yourself, it's just superslow.

**Comment by rancidfrog** [comment] 2020-04-26 02:14
@kiwibrowser 
Please use automated building to also add APKs to release section
Maybe, https://github.com/marketplace/actions/automatic-releases

**Comment by kiwibrowser** [comment] 2020-04-26 02:17
Doing it

**Comment by SimonBrazell** [comment] 2020-08-31 06:33
Will this happen soon?

Keen to give this a go now Firefox has broken extensions on Android, as I'm sure many are.

**Comment by Dev-i-l** [comment] 2020-10-18 06:23
@kayg04 you can close this issue as apks of latest versions can be downloaded from github

**Comment by IzzySoft** [comment] 2020-10-18 10:51
@Dev-i-l while that certainly is good, it's not the same (close, but no cigar). People trust F-Droid. People are constantly getting discouraged from installing apps they find "on some website". Plus, side-loading means you've got to care for updates manually.

I'd say it's still preferable having it available in "F-Droid proper". Your choice, of course.

**Comment by kiwibrowser** [comment] 2020-10-18 13:02
@IzzySoft 

As you can see in the Actions tab, the reproducible builds are working very well since that topic was started, but I need to create a separate repo for F-Droid; because on F-Droid you cannot distribute Chromium-based browsers in the main repository (and there are tons of good reasons to it).
I haven't checked the doc how to create a F-Droid repo, but it makes sense to do it, so let's keep in touch; it'll can be convenient to users.

**Comment by IzzySoft** [comment] 2020-10-18 13:51
Yes, definitely! Once it's there, I should put it into my list of available F-Droid repos.

In the forum, we recently had someone asking for help on setting up a repo; they managed themselves, but picked up some hints missing from the docs (like making sure the URL ends in `/fdroid/repo`, which the docs state without giving reason – it's so the intent filter picks it up and, if a user taps such an URL, the F-Droid client jumps in offering to add the repo). So basically, those docs should be quite straight to follow.

**Comment by bingoxo** [comment] 2021-01-27 10:38
any update on this ?

**Comment by hefty-fading-culprit-epiphany-drew** [comment] 2021-02-07 16:13
@kiwibrowser  Any update on this?

**Comment by hefty-fading-culprit-epiphany-drew** [comment] 2021-02-12 16:14
Enabling extension support requires some specific Google dependancies that's why ungoogled chromium on desktop doesn't come with extension support by default. So the chances of this happening is minimal. Really sad😞

**Comment by sleeplife** [comment] 2021-05-17 12:41
What do you think of "chromium-based" repo?
For all open source projects based on chromium 🤔

**Comment by d3ward** [comment] 2021-07-23 10:02
For now there is no plan to share Kiwi on F-droid .
If necessary a new discussione will be opened in [src.next](https://github.com/kiwibrowser/src.next)

**Closed by d3ward** 2021-07-23 10:02 UTC
Labels: Discussion
