### ISSUE TITLE
Maps are cannot be scrolled

### ISSUE THREAD

**Issue by Godecki** [kiwibrowser/src#162] opened 2020-09-11 12:45 UTC
On any site, where there is an implemented map it cannot be moved using two fingers. Like the browser doesn't detect pinching. Here is an example site with this problem:

https://www.pkobp.pl/poi/

**Comment by kiwibrowser** [comment] 2020-09-12 02:24
The issue is due to the popup blocker (as surprising as it seems), the browser believes that the javascript that is bound to DOM+mousedown is suspicious.

There is somewhat a whitelist, but it's not a smart implementation:
https://github.com/kiwibrowser/src/blob/b1ea3ea95d8ac15fc0b49acd83ba2f8b1aaa8d2b/third_party/blink/renderer/core/dom/events/event_target.cc#L780

I wonder how to find what is Google Maps (from a script perspective), maybe by checking the JavaScript execution stack

**Comment by Godecki** [comment] 2020-09-14 09:17
Thanks for the reply. I am not developer though, hope someone fixes it, lol

**Comment by MaxEtMoritz** [comment] 2020-09-17 11:19
maybe Related to this one: for me the mousedown seems to work, but the mouseup event doesn't on embedded Google Maps. I even disabled the popup blocking but the problem persists. E.g. if i swipe only with one finger, the overlay saying 'use two fingers to move the map' appears, but doesn't disappear. This issue causes embedded Google maps to keep focus and in some situations on some pages prevents me from scrolling up or down on the web page. an example map can be found here: [https://developers.google.com/maps/documentation/javascript/examples/map-simple](url)

**Comment by Oranko** [comment] 2021-07-22 13:17
Fixed in the latest version

**Closed** 2021-07-22 16:32 UTC
Labels: bug
