### ISSUE TITLE
Cannot paste

### ISSUE THREAD

**Issue by yaakovfeldman** [kiwibrowser/src#26] opened 2020-04-19 17:16 UTC
I cannot paste text into Web pages unless the text was copied within Kiwi. If I attempt to paste text copied from another app, the text actually pasted is the last thing I copied within Kiwi.

Occasionally (when phone first turned on after restart) I can paste something from outside Kiwi but only once.

This does not affect the url bar. I can always paste into that with no issues.

I have not had any similar issues with other apps including my usual browser (Firefox). 

I really like Kiwi otherwise and look forward to it being my main browser. 

Kiwi 77.0.3865.92 from play store on Samsung S10 running android 10. I disabled all extensions.

**Comment by MaxUNof** [comment] 2020-04-20 16:40
I have a similar problem.

**Comment by meniossin** [comment] 2020-04-24 12:11
Hey @yaakovfeldman , I tried replicating your issue on my Kiwi installation. (version 77.0.3865.92 runnign on Android 9.0.0; Redmi 6A). I tried pasting various texts from differents apps(Brave browser, FB messenger, whatsapp) without any problem whatsoever. As I notice, we're using the same kiwi version, so  maybe the problem it's due to the Android version(10) ? Maybe @d3ward knows if and how different Android versions could produce certain bugs like this one ?

**Comment by michallepicki** [comment] 2020-04-24 12:13
I have the same issue on a samsung s10e phone with android 10

**Comment by mfkp** [comment] 2020-04-27 03:14
Same issue.

This makes it very complicated pasting in 2fa codes, etc.

I've recorded a video of the issue to demonstrate (notice how it pastes is something completely different inside Kiwi Browser, which appears to be whatever was last copied inside the app).

[https://www.dropbox.com/s/u7ljr5ggys0ggjz/20-04-26-20-06-54.mp4?dl=0](https://www.dropbox.com/s/u7ljr5ggys0ggjz/20-04-26-20-06-54.mp4?dl=0)

**Comment by And96** [comment] 2020-04-30 17:38
Same issue on Xiaomi Mi9

Paste does not work if I am on an empty textbox (Eg: search, mail, password etc...)
It happens on every website.

If I type a letter then "paste" appears again.

I can confirm both Chrome and Firefox has same issue. So, it may not be related to Kiwi.

**Comment by yaakovfeldman** [comment] 2020-04-30 17:51
@And96 these are different symptoms to mine. For me, paste works fine in Chrome and Firefox, just not in Kiwi. And typing does not fix it, unfortunately.

**Comment by robsmith11** [comment] 2020-06-17 11:24
Same issue for me with a Huawei Mate 20 X and Android 10.

One thing I haven't seen mentioned is that paste seems to work fine for the URL bar, but any webpage textboxes have the issue.

**Comment by yjmn16** [comment] 2020-09-19 01:20
Many users are asking for a fix for this bug on the Play Store as well.

Do you have any plans to fix it?

Or is it a difficult problem that cannot be fixed?

I would like to know the developer's thoughts on fixing this bug.

**Comment by kiwibrowser** [comment] 2020-09-19 12:10
I just don't know how to reproduce this bug, I need to spend more time trying to reproduce.

I think the fix is only a couple of lines and/or some permission adjustments (I guess Kiwi is too strict)

This will be fixed in the coming days I think

**Comment by c35sys** [comment] 2020-09-24 21:33
If it can help, I have another behavior. 

I'm able to paste but only a previous copy and when I just close/open Kiwi web browser, I'm able to copy the correct copy (a password in my case). 

Huawei p20 android 10

**Comment by kotaro366** [comment] 2020-09-26 10:23
This is an example of a Play Store report.
Can't you reproduce with these methods?
please refer.
android 10

・If you don't close the app once, only the first copy will be reflected.
The next copy is not copied, the previous copy is pasted.

・When I try to copy and paste my email address and password to log in to google
Only the address is pasted and the password field remains the address even if pasted
You can first copy the email address from Notepad and paste it into the email address field.
Next, I want to copy the password and paste it into the password field, but the first copied email address is pasted.

・The string copied the first time can be pasted normally,
The character string copied from the second time onward will not be reflected at all.
No matter how many times I try, I can only paste the string that was copied the first time.

**Comment by kiwibrowser** [comment] 2020-10-02 20:20
Testing a fix @ https://github.com/kiwibrowser/src/commit/8419f2f07faf34d416ca50d7f924413dd0eb2eac (build is coming)

**Comment by c35sys** [comment] 2020-10-16 14:27
> If it can help, I have another behavior.
> 
> I'm able to paste but only a previous copy and when I just close/open Kiwi web browser, I'm able to copy the correct copy (a password in my case).
> 
> Huawei p20 android 10

It's working now on Kiwi Git201009, Android 10, thanks !

**Comment by yaakovfeldman** [comment] 2020-10-16 14:37
> I cannot paste text into Web pages unless the text was copied within Kiwi. If I attempt to paste text copied from another app, the text actually pasted is the last thing I copied within Kiwi.
> 
> Occasionally (when phone first turned on after restart) I can paste something from outside Kiwi but only once.
> 
> This does not affect the url bar. I can always paste into that with no issues.
> 
> I have not had any similar issues with other apps including my usual browser (Firefox).
> 
> I really like Kiwi otherwise and look forward to it being my main browser.
> 
> Kiwi 77.0.3865.92 from play store on Samsung S10 running android 10. I disabled all extensions.

Now working for me as well Samsung S10 Git201009 from Play store.

**Comment by kiwibrowser** [comment] 2020-10-16 16:46
Thank you @yaakovfeldman @c35sys for reviewing and testing that the issue was corrected.

I'll close the issue then.

**Closed by kiwibrowser** 2020-10-16 16:46 UTC
Labels: Type: Bug
