### ISSUE TITLE
custom download path in sdcard 

### ISSUE THREAD

**Issue by buvanbamm** [kiwibrowser/src#106] opened 2020-05-30 16:29 UTC
kiwi should also have it like mostly other downloading apk offers custom download path location.
for more details visit https://stackoverflow.com/questions/36862675/android-sd-card-write-permission-using-saf-storage-access-framework

>

**Comment by hjyoung1** [comment] 2020-05-30 18:54
Duplicate of #102

**Closed** 2021-07-23 16:47 UTC
